tazz4843/whisper-rs

src/whisper_params.rs
When I used set_language method. I got an error due to a lack of terminate char (‘\0’) and I fixed it.
I’m happy to review the PR and merge it!
code
```rust
let mut ctx = WhisperContext::new("models/ggml-base.bin").expect("Failed to load model.");
let mut params = FullParams::new(SamplingStrategy::Greedy { n_past: 0 });
params.set_language("ja");
let audio_data = read_wav("audio/output.wav");
let mut audio_data_float = whisper_rs::convert_integer_to_float_audio(&audio_data);
audio_data_float.push(0.0);
let audio_data = whisper_rs::convert_stereo_to_mono_audio(&audio_data_float);
ctx.full(params, &audio_data[..])
.expect("Failed to run model");
```
error (console output)
```
whisper_model_load: memory size =    22.83 MB 
whisper_model_load: model size  =   140.54 MB
whisper_lang_id: …
```
=> add conversion of &str to CString in set_language method

examples/basic_use.rs
Fixes error in example
##What did I do?
Ran `cargo run --example basic_use`  and saw that this error was produced.
```rust
error[E0599]: no method named `set_print_special_tokens` found for struct `FullParams` in the current scope
--> examples/basic_use.rs:23:12
|
23 |     params.set_print_special_tokens(false);
|            ^^^^^^^^^^^^^^^^^^^^^^^^ help: there is a method with a similar name: `set_print_special`
For more information about this error, try `rustc --explain E0599`.
```
I simply followed the recommendation of the awesome `rustc` compiler :)
=> Fixes error in example

sys/build.rs
This PR moves the build to use `cmake` instead of `make`. The reason is that `whisper.cpp` doesn't support building for Windows using `make` at the moment. Moreover (even if it did), `cmake` solves several issues such as figuring out which specific compiler version to use and so on.
I have tested that this works on Windows, and it definitely does (at least for Windows 11). I can't really test it on any other OS, so I would appreciate some help for that.
Aside from the move to `cmake`, the only other thing I think might be a problem is the `std::fs::copy` call for move whisper to the `OUT_DIR`. The issue is that different OS will have a differently-named output file. `cargo` knows this and deals with it accordingly, but how to do so in the script I'm unsure.
=> Fix build on Windows

Cargo.toml, examples/audio_transcription.rs, examples/basic_use.rs, src/utilities.rs
If you call convert_stereo_to_mono_audio(samples: &[f32]) with an odd number of samples, it panicked.
This was because the algorithm did a step by 2 and then accessed the value via an index of i+1, which will not exist at the end of a slice with an odd number of samples.
There were two possible solutions for this.
1. Return a result in case in the case that the number of elements is odd. This seems like a good option since it is in fact an error (you shouldn't have a half sample of data), but would require an API change externally.
2. Drop the last half sample. This is simpler.
In this pull request, I implemented the second option for simplicity. In the process, I also simplified the code into one functional line that uses collect, which is usually faster.
Implementing the first version …
=> Fix panic in stereo to mono audio conversion

sys/build.rs
I was running into an issue building `whisper-rs` inside a docker image, I believe due to a newer cmake version:
Here's the relevant error msg
```
..
#11 214.0   -- Generating done
#11 214.0   -- Build files have been written to: /usr/local/cargo/git/checkouts/whisper-rs-c8b9fa7c09c8c913/cf27802/sys/whisper.cpp/build
#11 214.0 
#11 214.0   --- stderr
#11 214.0   Unknown argument --config Release
#11 214.0   Usage: cmake --build <dir> [options] [-- [native-options]]
...
```
It ended up being a simple fix, just splitting up those args got it working. Tested working outside of the docker image as well.
=> cmake build args fix

BUILDING.md
- updated whisper-cpp to v1.3.0 because the build in MSVC is ok after update whisper-cpp to v1.3.0
- whisper-cpp's MSVC build had problem from Japanese character "『" and "』" encoding problem
- MSVC missleaded the file has SJIS but after v1.3.0, CMakeList.txt configure it is UTF-8 explicitly so now MSVC can build it.
- And I had tested it with MSVC clean environment. Just following is reportable:
- we need to add three dependencies for this build. We need to add these dependencies for PATH.
- 1. MSVC itself
- 2. CMake
- 3. LLVM(clang)
- It seems buildable it by `cargo` so we don't need to build it from git repository.
- So I had rewrite `BUILDING.md`
=> Support for MSVC environment

src/error.rs
- `impl std::error::Error for WhisperError` to improve error compatibility.
- Also impl `std::fmt::Display` for the struct because the implementation is required from `std::error::Error`.
- `std::error::Error` is the trait for expressing errors in standard.
- And some of error handling libraries requires Error implemented struct for Result.
- for examples: `error-stack` have default `std::error::Error` implementation for `Context` struct.
=> impl Error to improve compatibility

Cargo.toml, sys/Cargo.toml, sys/build.rs
I've added a feature to whisper-rs and whisper-rs-sys that will build whisper.cpp with Apple CoreML support. This improves execution time by 3x-5x on my MacBook Air M1.
In addition to adding -DWHISPER_COREML=1 to the cmake arguments as documented in the whisper.cpp README, building whisper-rs-sys requires adding the Foundation and CoreML frameworks and linking to an additional generated library, libwhisper.coreml.a.
To generate the CoreML models, you will need to have XCode installed. Converting and loading the larger models (small+) may require a significant amount of time; I have not yet been able to successfully convert the medium or large models on my system. Hopefully a future whisper.cpp version will support enabling and disabling CoreML at run time.
=> Add coreml feature flag and build.rs updates

sys/build.rs
In windows, we are using `libwhisper.lib` instead of `libwhisper.a` so renamed it.
=> fix: error message for libwhisper.lib

src/error.rs, src/whisper_ctx.rs, src/whisper_state.rs
- Add lifetime parameter for WhisperState and now the instance cannot alive over than WhisperContext instance.
- Change WhisperContext interface by using WhisperState directly instead of Map from the key to State.
- Remove errors related for such keys
refer: #37
=> refactor: delete map for State and expose struct with lifetime

src/lib.rs
It needs to construct `WhisperState` on user code side.
Related: https://github.com/tazz4843/whisper-rs/pull/39
=> fix: public WhisperState from lib

Cargo.toml, src/whisper_ctx.rs
This pull request converts the text parameter to a CString. It also includes a round trip test behind a feature gate that requires that the tiny.en model has been downloaded into `sys/whisper.cpp/models/`.
I think it might be worthwhile having a discussion about how to deal with models for tests and examples, and whether it should be done explicitly by the user or automatically by build.rs when a feature flag is specified. Alternatively, we could have a dedicated crate that includes a snapshot of the tiny.en model. This would be very useful for CI purposes.
=> Tokenize with cstring

src/whisper_ctx.rs
I've refactored `token_to_str` to use `token_to_cstr` internally.
`token_to_str` actually returns a `String`, which may be confusing. I'd suggest changing the function to return a `&str` to match expectations. This also allows the user to decide whether to allocate or not.
=> Add token_to_cstr

sys/build.rs
1.4.1 added an additional CMake flag to allow fallback when the CoreML model is not found, but it turns out there is a bug in the implementation: https://github.com/ggerganov/whisper.cpp/pull/893
Posting this here for when that fix is applied and in case anyone else runs into this problem.
=> Allow fallback to GGML when CoreML model not available.

sys/Cargo.toml
The opencl feature can't possibly work without including the actual code.
=> include ggml-opencl in the crate

sys/build.rs
This allows whipser-rs-sys to work when building a cdylib on x86 Linux
in certain conditions.
Without this change, linking can fail with:
```
= note: /usr/bin/ld: /.../target/debug/deps/libwhisper_rs_sys-d9be91f496c91a32.rlib(whisper.cpp.o): warning: relocation against `_ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE@@GLIBCXX_3.4.21' in read-only section `.text.unlikely'
/usr/bin/ld: /.../target/debug/deps/libwhisper_rs_sys-d9be91f496c91a32.rlib(whisper.cpp.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
```
Note that this is one solution. I believe another would be to use the [cmake …
=> Use position independent code (-fPIC)

README.md
I tried running the example in the README, but it failed with a bunch of errors such as:
```
error[E0599]: no method named `full_n_segments` found for struct `WhisperContext` in the current scope
```
after looking through the docs, this change seemed like the right thing to do. I tried it and it seems to have worked, resulting in the output like:
```
...
whisper_full_with_state: progress =  90%
whisper_full_with_state: progress =  95%
whisper_full_with_state: progress = 100%
[0 - 200]:  You
```
Additionally, I made the `path_to_model` a CLI param.
=> Fix/update example in the README

sys/build.rs
I've built whisper-rs on both OSX and Linux, and after the build it shows that the file `bindings/javascript/package.json` has been removed the whisper.cpp directory.  It seems like this is intentional, but it causes issues because package.json is a committed file that's part of the whisper.cpp repo.  See:
https://github.com/ggerganov/whisper.cpp/blob/master/bindings/javascript/package.json
With this change, I do not get any cargo warnings when building on either system, so perhaps whatever was causing the warning earlier has been addressed by a later change.
Feel free to ignore this PR if your experience is different, just wanted to share!
=> don't remove bindings/javascript/package.json during build

README.md
For anyone just looking to validate that they can indeed build and run the examples on their own computer, the README is missing the important note that `git clone` must be given the `--recursive` flag. Without that flag, the result is a baffling error (see below). This PR [adds instructions](https://github.com/artob/whisper-rs/blob/improve-readme/README.md) for cloning and running the examples.
```console
% cargo run --example basic_use
Compiling memchr v2.5.0
Compiling libc v0.2.146
Compiling proc-macro2 v1.0.60
Compiling glob v0.3.1
Compiling quote v1.0.28
Compiling unicode-ident v1.0.9
Compiling minimal-lexical v0.2.1
Compiling syn v1.0.109
Compiling cfg-if v1.0.0
Compiling bindgen v0.64.0
Compiling libloading v0.7.4
Compiling either v1.8.1
Compiling regex-syntax v0.7.2
Compiling …
```
=> Add instructions for running the examples

src/whisper_state.rs
Based on how whisper.cpp stores the mel spectrogram internally, this is what we need here: mel.n_len is the stride in the time domain. I've successfully passed the JFK test by passing in a spectrogram alone, but this change is required to make it work. 
more info in my implementation:
https://github.com/wavey-ai/mel_spec/blob/3373c64d9e3200485d96c3730b5e6430be074583/src/lib.rs#L141C4-L141C4
https://github.com/wavey-ai/mel_spec/blob/main/src/lib.rs#L475
I'm happy to move some/all of this code into whisper-rs at some point. `set_mel` can't really be used without something like this - it took a while to figure out - but not sure if the stft stuff is a bit out of scope, or not.
=> calculate mel.n_len as mel spectrogram stride len

examples/full_usage/src/main.rs, src/whisper_params.rs
This is a proof-of-concept. I will extend the docs once I get maintainer feedback.
- the callback is not called as frequently as the progress print. See the example output:
```
[02:11:22 PM] $ cargo run -- 2830-3980-0043.wav ~/build/whisper.cpp/models/ggml-base.en.bin
Finished dev [unoptimized + debuginfo] target(s) in 0.14s
Running `target/debug/full_usage 2830-3980-0043.wav /home/marcin/build/whisper.cpp/models/ggml-base.en.bin`
whisper_init_from_file_no_state: loading model from '/home/marcin/build/whisper.cpp/models/ggml-base.en.bin'
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51864
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 512
whisper_model_load: n_audio_head  = 8
whisper_model_load: n_audio_layer = 6
whisper_model_load: …
```
=> Add a rustified progress callback.

sys/build.rs, sys/wrapper.h
Functions like `ggml_cpu_has_avx` might be useful for downstream consumers.
=> Expose the ggml functions in the bindings.

src/standalone.rs
Probably a better way would be to write a proc macro to derive the default implementation, but I feel it's an overkill.
=> Safely expose some of the ggml_cpu_has... routines

sys/Cargo.toml, sys/build.rs
Hi, @tazz4843 !
I've made some effort to simplify cmake machinery and make build sandbox-friendly (now it is not changing source directory), now this crate can be build with NIX Flake.
Any feedback appreciable!
=> Sandbox friendly build

Cargo.toml, sys/Cargo.toml, sys/build.rs
Should hopefully fix errors along the lines of the following on macOS:
```
Undefined symbols for architecture x86_64:
"_MTLCopyAllDevices", referenced from:
_ggml_metal_init in libwhisper_rs_sys-3c0021a7bf9aa3b1.rlib(ggml-metal.m.o)
"_MTLCreateSystemDefaultDevice", referenced from:
_ggml_metal_init in libwhisper_rs_sys-3c0021a7bf9aa3b1.rlib(ggml-metal.m.o)
"_OBJC_CLASS_$_MTLComputePassDescriptor", referenced from:
objc-class-ref in libwhisper_rs_sys-3c0021a7bf9aa3b1.rlib(ggml-metal.m.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
```
ggml_metal_init: allocating
ggml_metal_init: found device: AMD Radeon Pro 5500M
ggml_metal_init: found device: Intel(R) UHD Graphics 630
ggml_metal_init: picking default …
```
=> Add a feature flag for Metal acceleration support

README.md, examples/audio_transcription.rs, examples/basic_use.rs, examples/full_usage/src/main.rs, src/lib.rs
@tazz4843 I've tested your whisper.cpp-1.5 branch.
Looks good, found 1 small issue, WhisperContextParameters wasn't added to `src/lib.rs`. Also updated examples to not use the deprecated `WhisperContext::new(&str)`.
=> Expose WhisperContextParameters and update examples

src/lib.rs, src/whisper_ctx.rs
I found 2 more issues
- `WhisperGrammar` and `WhisperGrammarElementType` weren't exposed by `lib.rs` so you couldn't make an object to pass to `ctx.set_grammar(Option<&[WhisperGrammarElement]>)`
- You couldn't create a custom `WhisperContextParameters` to pass to `WhisperContext.new_with_x` since you'd get a borrow checker issue as soon as you tried to call `ctx_params.use_gpu(true)` because it was moving the object not borrowing.
=> Additional WhisperGrammar and WhisperContextParameters fixes

src/error.rs, src/whisper_state.rs
I've been randomly getting segmentation faults in whisper.cpp. Finally managed to capture and dig into a coredump. Common thread between all of them is they have zero samples. While this is a bug I need to fix myself, this is also a major footgun.
=> Fix possible segmentation fault

src/whisper_grammar.rs, sys/build.rs
I tried to use this library on windows inside `msys2`, following `BUILDING.md` and got bunch of erros.
Fixed all of them and planning to improve the instructions as well. 
Checked in msys2 and it works with the examples of this repo.
https://github.com/tazz4843/whisper-rs/issues/87
https://github.com/tazz4843/whisper-rs/issues/65
Steps to build:
1. Download `msys2` from https://www.msys2.org/ and install
2. Install prerequisites from `ucrt64` terminal
```console
pacman --needed -S $MINGW_PACKAGE_PREFIX-{toolchain,make,cmake,rust,clang} git
```
3. Clone
```console
git clone -b fix/msys2-build --recursive https://github.com/thewh1teagle/whisper-rs.git
cd whisper-rs
```
4. Build
```console
cargo build
```
5. Try it
```console
wget -q --show-progress \ …
```
=> fix windows gnu build

Cargo.toml, src/error.rs, src/lib.rs, src/utilities.rs
* Avoids allocations in convert_integer_to_float_audio by taking an input buffer
* convert_stereo_to_mono_audio now returns WhisperError instead of &'static str in the Err case
* All errors are converted to WhisperError types
* Testing mod gets extra utilities
=> Update audio utilities

sys/build.rs
add the missing 'cuda' lib, otherwise, link failed on windows with cuda feature enabled
=> fix: LNK2019: unresolved external symbol cuGetErrorString

src/whisper_params.rs
Add safe bindings to abort callback so it will be able to cancel transcription.
=> feat: add safe bindings to abort callback

src/whisper_state.rs
Add `full_get_segment_text_lossy` so it wont crash in case that whisper return some invalid characters.
Resolve https://github.com/tazz4843/whisper-rs/issues/115 
Tested in https://github.com/thewh1teagle/vibe/issues/39
=> feat: add get segment text lossy

examples/full_usage/src/main.rs, src/lib.rs, src/whisper_ctx.rs, src/whisper_ctx_wrapper.rs, src/whisper_state.rs
I encountered difficulties using the state correctly in callbacks due to challenges with the borrow checker. I adopted the approach suggested by @jcsoo in this discussion: https://github.com/tazz4843/whisper-rs/issues/86#issuecomment-2058049340.
Here's a summary of the refactoring changes:
1. Retain the original WhisperContext as the internal context, used privately within both the WhisperContext wrapper and WhisperState.
2. Designate the wrapper as WhisperContext and proxy all methods to the inner context, ensuring the public API remains unchanged.
I'd appreciate your feedback on this approach :)
=> To improve the usability of WhisperState with Rust's borrow checker

sys/build.rs
On Linux, libcuda is located in the "stubs" sub folder.
=> fix: Can't find libcuda when build with cuda feature on Linux

sys/build.rs
Allow passing cmake flags to whisper from environment variables when compiling `whisper-rs`
Example flags: [CMakeLists.txt#L66C0-L72C0](https://github.com/ggerganov/whisper.cpp/blob/c7b6988678779901d02ceba1a8212d2c9908956e/CMakeLists.txt#L66C0-L72C0)
=> feat(sys): pass whisper cmake flags from environment variables

Cargo.toml, src/whisper_state.rs, sys/Cargo.toml, sys/build.rs
This is a fix for lang_detect function, return value changed a bit to return detected language id and array with probabilities of all languages.
Also I've enabled debug logs in whisper.cpp for debug builds.
=> fix: lang_detect not working properly

sys/build.rs
To test it on windows:
```console
wget "https://github.com/OpenMathLib/OpenBLAS/releases/download/v0.3.26/OpenBLAS-0.3.26-x64.zip"
"C:\Program Files\7-Zip\7z" x OpenBLAS-0.3.26-x64.zip -oopenblas
set OPENBLAS_PATH=%cd%\openblas
cargo run --example basic_use --features "openblas"
```
=> fix: link openblas path correctly

build.rs, src/lib.rs, sys/build.rs
Add a `WHISPER_CPP_VERSION` static that contains the version number of whisper.cpp that whisper-rs was built with. This can be useful for downstream applications for debugging and logging purposes.
This is implemented using [build script metadata](https://doc.rust-lang.org/cargo/reference/build-scripts.html#the-links-manifest-key) for whisper-rs-sys to expose the version number of whisper.cpp defined in `CMakeLists.txt` as metadata to crates that depend on it. Then whisper-rs accesses that build metadata and defines its own internal compile-time environment variable containing the same value, which is then assigned to a static variable.
It seemed better to expose this information through build metadata rather than defining a static in whisper-rs-sys directly, despite the extra …
=> Expose whisper.cpp version as a static string

sys/build.rs
The PR fix the build on macos when targeting the vulkan backend. 
Targeting the master branch will result in ld failing to link against vulkan. See [GH action log](https://github.com/newfla/simple-whisper/actions/runs/10898814262/job/30242820759).
With the updated build.rs build process is fine [step _check whisper-rs vulkan build_](https://github.com/newfla/simple-whisper/actions/runs/10905411811/job/30264175328).
=> fix: macos vulkan build script

sys/build.rs
The file `libwhisper.coreml.a` placed in `build/src`.
=> fix: add search path for coreml on macOS

.github/workflows/pr.yml, Cargo.toml
Make OpenMP optional to improve compatibility with MacOS
Currently, OpenMP is specified as a default dependency in Cargo.toml. However, OpenMP is not installed by default on MacOS systems, which can cause unexpected build failures, especially in CI environments like GitHub Actions macOS runners.
- Remove OpenMP from default features
- Make it available as an optional dependency, similar to whisper.cpp's approach
- Better out-of-the-box experience on MacOS
- No additional libomp installation required for basic builds
- Improved CI/CD workflow, especially on macOS runners
- More flexible dependency management for users
Users who want to use OpenMP can still enable it explicitly through features.
=> Make OpenMP optional instead of default dependency

src/whisper_ctx.rs
Add the support for v3turbo dtw preset introduced by [whisper.cpp#2481 commit](https://github.com/ggerganov/whisper.cpp/pull/2481)
=> feat: large v3 turbo dtw preset

.gitmodules, src/standalone.rs, src/whisper_params.rs, sys/build.rs
This PR is based on the changes by @thewh1teagle and the PR #193 
I forked @thewh1teagle 's fork, applied the changes, changed whisper.cpp back to the original repository and pushed the submodule to the latest whisper.cpp version. Also, I renamed the `set_suppress_non_speech_tokens`-function to `set_suppress_nst`.
I tested it in a tauri macOS and iOS app, it works very good.
=> Update whisper.cpp to v1.7.4; rename suppress_nst

sys/build.rs
This is a minor bugfix. When I tried to build whisper-rs with cuda, I noticed that the linker is never told explicitly to link the library `ggml-cuda.lib`. This pr should fix the problem.
=> link cuda when cuda feature is on

src/whisper_params.rs
Starting from v0.13.0 `set_segment_callback_safe_lossy` and `set_segment_callback_safe`  (due to internal changes from whisper.cpp).
The PR has been tested on single segment file audio and [multiple segment audio](https://replicate.delivery/mgxm/e5159b1b-508a-4be4-b892-e1eb47850bdc/OSR_uk_000_0050_8k.wav)
@tazz4843 a new crates release would be very welcome :D
=> fix: segment_callaback logic

sys/build.rs
In some non-English language environments, building sys crate on Windows fails.
For example, if the Windows system language is set to Japanese, the default system charset is CP932.
=> Use UTF-8 to build whisper.cpp on Windows

src/whisper_params.rs
Revert my commit and add a disclaimer on the interaction between dtw and segment_callback.
Close #208
=> Revert "fix: segment_callaback logic" 

README.md
The feature flags seem to have changed from `whisper-cpp-tracing` and `whisper-cpp-log` to `tracing_backend` and `log_backend` at some point.
This PR is just a simple doc fix to update references to these flags in the `README.md`.
=> doc: fixed feature flag names in README.md

sys/build.rs
... I'm getting `undefined symbol: ggml_backend_blas_reg` otherwise.
```
= note: some arguments are omitted. use `--verbose` to show all linker arguments                                                                             
= note: mold: error: undefined symbol: ggml_backend_blas_reg                                                                                                 
>>> referenced by ggml-backend-reg.cpp                                                                                                               
>>>               /home/kaspar/src.old/own/whisper-http-service/target/debug/deps/libwhisper_rs_sys-4616210e579be9da.rlib(ggml-backend-reg.cpp.o):(gg
ml_backend_registry::ggml_backend_registry()) …
```
=> fix: static link `ggml-blas` if openblas feature is enabled

sys/build.rs
Resolves a linker error when building with feature `cuda`, such that nvcc compiled & linked objects get compiled with position-independent code (`-fPIC`). I noticed that this was not getting done when building `whisper-rs` into https://github.com/mz2/pipescribe: when enabling the `cuda` feature, `cargo`, the following linker error would occur:
```
...
"-L" "<sysroot>/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/home/mz2/Developer/pipescribe/gui/rust/target/debug/deps/librust_lib_pipescribe.so" "-Wl,--gc-sections" "-shared" "-Wl,-z,relro,-z,now" "-nodefaultlibs"
= note: some arguments are omitted. use --verbose to show all linker arguments
= note: /usr/bin/ld: /home/mz2/Developer/pipescribe/gui/rust/target/debug/deps/libwhisper_rs_sys-193aab817605690a.rlib(fattn.cu.o): warning: …
```
=> Fix CUDA linking error by ensuring -fPIC for position-independent code

sys/build.rs
GGML_HIPBLAS was renamed to GGML_HIP as part of the library refactoring work in [llama.cpp](https://github.com/ggml-org/llama.cpp/pull/10256) and then subsequently ported to [whisper.cpp](https://github.com/ggml-org/whisper.cpp/pull/2573/commits/ce58be7e79e96007759ad44a31caf40730940452).
This fix now allows this library to be compiled with rocm v6.
=> fix: Correct broken hipblas build

src/lib.rs, src/vulkan.rs, sys/build.rs, sys/wrapper.h
Adds a safe Rust wrapper for **Vulkan GPU enumeration** that mirrors the SYCL request in #160 but targets the `ggml_backend_vk_*` APIs instead.
* **build.rs**
* allow-lists the following symbols when the `vulkan` feature is enabled  
`ggml_backend_vk_get_device_count`, `ggml_backend_vk_get_device_description`,  
`ggml_backend_vk_get_device_memory`, `ggml_backend_vk_buffer_type`
* **src/backend/vulkan.rs**
* `VkDeviceInfo` — human-readable metadata (name, VRAM, buffer type)  
* `list_devices()` — returns `Vec<VkDeviceInfo>` in discrete-then-integrated order
* **tests**
* `enumerate_must_not_panic`  
* `sane_device_info`
Selecting the optimal GPU at runtime is vital on multi-GPU rigs (e.g. dGPU + iGPU).  
While ggml already exposes Vulkan back-end helpers, whisper-rs could not reach them. …
=> Add Vulkan GPU enumeration support (related to #160)

Cargo.toml, sys/Cargo.toml, sys/build.rs
Adding Intel Sycl with the feature flag `intel-sycl` to it. Static linking the intel sycl isn't possible, that's the reason why it's dynamic linked.
Compiling the crate with static linking is working, but then I get that weird linker error on runtime level. I was only able to solve that problem by linking it dynamically.
The logs when I tried it staticly:
```
Compiling whisper-rs-sys v0.13.0 (/home/kerkmann/git/whisper-rs-recu/sys)
Compiling whisper-rs v0.14.3 (/home/kerkmann/git/whisper-rs-recu)
Compiling opentalk-transcription v0.1.0 (/home/kerkmann/git/transcription)
error: linking with `clang` failed: exit status: 1
|
= note: some arguments are omitted. use `--verbose` to show all linker arguments
= note: ld.lld: error: undefined symbol: _intel_fast_memcpy
>>> referenced by …
```
=> feat: add intel sycl support
